// Code generated by "stringer -type=BOXTYPE -trimprefix=BoxType"; DO NOT EDIT.

package boxes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COCO-0]
	_ = x[PASCAL-1]
}

const _BOXTYPE_name = "COCOPASCAL"

var _BOXTYPE_index = [...]uint8{0, 4, 10}

func (i BOXTYPE) String() string {
	if i >= BOXTYPE(len(_BOXTYPE_index)-1) {
		return "BOXTYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BOXTYPE_name[_BOXTYPE_index[i]:_BOXTYPE_index[i+1]]
}
